# Welcome! I'm sCRAP. Can I hep you?

In [ ]:
from sCRAP_the_robot import *
#pip install lxml

###  To see how the robot works, go back to the repository and have a look on the pdf schemat and attached python modules first (highly recommended)


###  To test it yourself, feel free to formulate your collector and check the new records is the database. The collector object hodls 3 arguments 

Here are the instructions: 


    - The link to a particular eshop - sCRAP should know CZC.CZ and DATART, however, the performance of DATART REQUESTS is unstable. (there in general a lot to fix) - it'srecommendedto use "https://www.czc.cz/"
    
    - The category string - use ANY you find on the website, e.g. "kalkulacky", "streamovani-herni-prislusenstvi" are good choices - they don't take that much time to scrape
    
    - Third argument is the period - in other words, if you want to rescan the web several times, how many seconds sould pass between the two consecutive attemts? If you wish to scrape the page only once, fill any integer. 
    
    - Last but not least, you can specify how many iterations you want to run in the fourth argument.

In [11]:
#Example colectors:
c = collect("https://www.czc.cz/","kalkulacky",10,3)

#c = collect("https://www.czc.cz/","notebooky",1,1)

You are about to start scraping the kalkulacky category. The page will be re-scanned every 10 seconds, in total 3 times
Current table for product data: product1579368832
Current table for soups: soup1579368832
Storage is ready. Data collection is about to start. The scraped data will be stored in *storage.db* database in your woking directory /n
Successfully requested the first czc homepage soup
4 pages found

88 items found

Product page urls were generated
1th product page from czc eshop successfully requested

2th product page from czc eshop successfully requested

3th product page from czc eshop successfully requested

4th product page from czc eshop successfully requested

Data upload just started

Recod 1/88 was added in the database

Recod 2/88 was added in the database

Recod 3/88 was added in the database

Recod 4/88 was added in the database

Recod 5/88 was added in the database

Recod 6/88 was added in the database

Recod 7/88 was added in the database

Recod 8/88 was added in the database

Recod 9/88 was added in the database

Recod 10/88 was added in the database

Recod 11/88 was added in the database

Recod 12/88 was added in the database

Recod 13/88 was added in the database

Recod 14/88 was added in the database

Recod 15/88 was added in the database

Recod 16/88 was added in the database

Recod 17/88 was added in the database

Recod 18/88 was added in the database

Recod 19/88 was added in the database

Recod 20/88 was added in the database

Recod 21/88 was added in the database

Recod 22/88 was added in the database

Recod 23/88 was added in the database

Recod 24/88 was added in the database

Recod 25/88 was added in the database

Recod 26/88 was added in the database

Recod 27/88 was added in the database

Recod 28/88 was added in the database

Recod 29/88 was added in the database

Recod 30/88 was added in the database

Recod 31/88 was added in the database

Recod 32/88 was added in the database

Recod 33/88 was added in the database

Recod 34/88 was added in the database

Recod 35/88 was added in the database

Recod 36/88 was added in the database

Recod 37/88 was added in the database

Recod 38/88 was added in the database

Recod 39/88 was added in the database

Recod 40/88 was added in the database

Recod 41/88 was added in the database

Recod 42/88 was added in the database

Recod 43/88 was added in the database

Recod 44/88 was added in the database

Recod 45/88 was added in the database

Recod 46/88 was added in the database

Recod 47/88 was added in the database

Recod 48/88 was added in the database

Recod 49/88 was added in the database

Recod 50/88 was added in the database

Recod 51/88 was added in the database

Recod 52/88 was added in the database

Recod 53/88 was added in the database

Recod 54/88 was added in the database

Recod 55/88 was added in the database

Recod 56/88 was added in the database

Recod 57/88 was added in the database

Recod 58/88 was added in the database

Recod 59/88 was added in the database

Recod 60/88 was added in the database

Recod 61/88 was added in the database

Recod 62/88 was added in the database

Recod 63/88 was added in the database

Recod 64/88 was added in the database

Recod 65/88 was added in the database

Recod 66/88 was added in the database

Recod 67/88 was added in the database

Recod 68/88 was added in the database

Recod 69/88 was added in the database

Recod 70/88 was added in the database

Recod 71/88 was added in the database

Recod 72/88 was added in the database

Recod 73/88 was added in the database

Recod 74/88 was added in the database

Recod 75/88 was added in the database

Recod 76/88 was added in the database

Recod 77/88 was added in the database

Recod 78/88 was added in the database

Recod 79/88 was added in the database

Recod 80/88 was added in the database

Recod 81/88 was added in the database

Recod 82/88 was added in the database

Recod 83/88 was added in the database

Recod 84/88 was added in the database

Recod 85/88 was added in the database

Recod 86/88 was added in the database

Recod 87/88 was added in the database

Recod 88/88 was added in the database

All changes successfully commited

1 iteration out of 3 commited, next to be starter in 0.16666666666666666 mins

Successfully requested the first czc homepage soup
4 pages found

88 items found

Product page urls were generated
1th product page from czc eshop successfully requested

2th product page from czc eshop successfully requested

3th product page from czc eshop successfully requested

4th product page from czc eshop successfully requested

Data upload just started

Recod 1/88 was added in the database

Recod 2/88 was added in the database

Recod 3/88 was added in the database

Recod 4/88 was added in the database

Recod 5/88 was added in the database

Recod 6/88 was added in the database

Recod 7/88 was added in the database

Recod 8/88 was added in the database

Recod 9/88 was added in the database

Recod 10/88 was added in the database

Recod 11/88 was added in the database

Recod 12/88 was added in the database

Recod 13/88 was added in the database

Recod 14/88 was added in the database

Recod 15/88 was added in the database

Recod 16/88 was added in the database

Recod 17/88 was added in the database

Recod 18/88 was added in the database

Recod 19/88 was added in the database

Recod 20/88 was added in the database

Recod 21/88 was added in the database

Recod 22/88 was added in the database

Recod 23/88 was added in the database

Recod 24/88 was added in the database

Recod 25/88 was added in the database

Recod 26/88 was added in the database

Recod 27/88 was added in the database

Recod 28/88 was added in the database

Recod 29/88 was added in the database

Recod 30/88 was added in the database

Recod 31/88 was added in the database

Recod 32/88 was added in the database

Recod 33/88 was added in the database

Recod 34/88 was added in the database

Recod 35/88 was added in the database

Recod 36/88 was added in the database

Recod 37/88 was added in the database

Recod 38/88 was added in the database

Recod 39/88 was added in the database

Recod 40/88 was added in the database

Recod 41/88 was added in the database

Recod 42/88 was added in the database

Recod 43/88 was added in the database

Recod 44/88 was added in the database

Recod 45/88 was added in the database

Recod 46/88 was added in the database

Recod 47/88 was added in the database

Recod 48/88 was added in the database

Recod 49/88 was added in the database

Recod 50/88 was added in the database

Recod 51/88 was added in the database

Recod 52/88 was added in the database

Recod 53/88 was added in the database

Recod 54/88 was added in the database

Recod 55/88 was added in the database

Recod 56/88 was added in the database

Recod 57/88 was added in the database

Recod 58/88 was added in the database

Recod 59/88 was added in the database

Recod 60/88 was added in the database

Recod 61/88 was added in the database

Recod 62/88 was added in the database

Recod 63/88 was added in the database

Recod 64/88 was added in the database

Recod 65/88 was added in the database

Recod 66/88 was added in the database

Recod 67/88 was added in the database

Recod 68/88 was added in the database

Recod 69/88 was added in the database

Recod 70/88 was added in the database

Recod 71/88 was added in the database

Recod 72/88 was added in the database

Recod 73/88 was added in the database

Recod 74/88 was added in the database

Recod 75/88 was added in the database

Recod 76/88 was added in the database

Recod 77/88 was added in the database

Recod 78/88 was added in the database

Recod 79/88 was added in the database

Recod 80/88 was added in the database

Recod 81/88 was added in the database

Recod 82/88 was added in the database

Recod 83/88 was added in the database

Recod 84/88 was added in the database

Recod 85/88 was added in the database

Recod 86/88 was added in the database

Recod 87/88 was added in the database

Recod 88/88 was added in the database

All changes successfully commited

0 iteration out of 3 commited, next to be starter in 0.16666666666666666 mins

2 iteration out of 3 commited, next to be starter in 0.16666666666666666 mins

Successfully requested the first czc homepage soup
4 pages found

88 items found

Product page urls were generated
1th product page from czc eshop successfully requested

2th product page from czc eshop successfully requested

3th product page from czc eshop successfully requested

4th product page from czc eshop successfully requested

Data upload just started

Recod 1/88 was added in the database

Recod 2/88 was added in the database

Recod 3/88 was added in the database

Recod 4/88 was added in the database

Recod 5/88 was added in the database

Recod 6/88 was added in the database

Recod 7/88 was added in the database

Recod 8/88 was added in the database

Recod 9/88 was added in the database

Recod 10/88 was added in the database

Recod 11/88 was added in the database

Recod 12/88 was added in the database

Recod 13/88 was added in the database

Recod 14/88 was added in the database

Recod 15/88 was added in the database

Recod 16/88 was added in the database

Recod 17/88 was added in the database

Recod 18/88 was added in the database

Recod 19/88 was added in the database

Recod 20/88 was added in the database

Recod 21/88 was added in the database

Recod 22/88 was added in the database

Recod 23/88 was added in the database

Recod 24/88 was added in the database

Recod 25/88 was added in the database

Recod 26/88 was added in the database

Recod 27/88 was added in the database

Recod 28/88 was added in the database

Recod 29/88 was added in the database

Recod 30/88 was added in the database

Recod 31/88 was added in the database

Recod 32/88 was added in the database

Recod 33/88 was added in the database

Recod 34/88 was added in the database

Recod 35/88 was added in the database

Recod 36/88 was added in the database

Recod 37/88 was added in the database

Recod 38/88 was added in the database

Recod 39/88 was added in the database

Recod 40/88 was added in the database

Recod 41/88 was added in the database

Recod 42/88 was added in the database

Recod 43/88 was added in the database

Recod 44/88 was added in the database

Recod 45/88 was added in the database

Recod 46/88 was added in the database

Recod 47/88 was added in the database

Recod 48/88 was added in the database

Recod 49/88 was added in the database

Recod 50/88 was added in the database

Recod 51/88 was added in the database

Recod 52/88 was added in the database

Recod 53/88 was added in the database

Recod 54/88 was added in the database

Recod 55/88 was added in the database

Recod 56/88 was added in the database

Recod 57/88 was added in the database

Recod 58/88 was added in the database

Recod 59/88 was added in the database

Recod 60/88 was added in the database

Recod 61/88 was added in the database

Recod 62/88 was added in the database

Recod 63/88 was added in the database

Recod 64/88 was added in the database

Recod 65/88 was added in the database

Recod 66/88 was added in the database

Recod 67/88 was added in the database

Recod 68/88 was added in the database

Recod 69/88 was added in the database

Recod 70/88 was added in the database

Recod 71/88 was added in the database

Recod 72/88 was added in the database

Recod 73/88 was added in the database

Recod 74/88 was added in the database

Recod 75/88 was added in the database

Recod 76/88 was added in the database

Recod 77/88 was added in the database

Recod 78/88 was added in the database

Recod 79/88 was added in the database

Recod 80/88 was added in the database

Recod 81/88 was added in the database

Recod 82/88 was added in the database

Recod 83/88 was added in the database

Recod 84/88 was added in the database

Recod 85/88 was added in the database

Recod 86/88 was added in the database

Recod 87/88 was added in the database

Recod 88/88 was added in the database

All changes successfully commited

1 iteration out of 3 commited, next to be starter in 0.16666666666666666 mins

## Here, you can check the scraped data in your database

In [12]:
data_storage = sqlite3.connect('storage.db')
pd.DataFrame(data_storage.execute("SELECT * FROM {}".format(c.product_tablename)).fetchall()).sort_values(4)

                       0           1                     2     3           4
0    https://www.czc.cz/  kalkulacky  Casio FX 350 ES PLUS   389  1579368832
63   https://www.czc.cz/  kalkulacky     Canon LS-123K-MOR   259  1579368832
62   https://www.czc.cz/  kalkulacky     Sencor SEC 160 GN   169  1579368832
61   https://www.czc.cz/  kalkulacky        Sencor SEC 180   129  1579368832
60   https://www.czc.cz/  kalkulacky      Casio HL 815L BK    99  1579368832
..                   ...         ...                   ...   ...         ...
200  https://www.czc.cz/  kalkulacky     Canon LS-123K-MBL   259  1579368875
199  https://www.czc.cz/  kalkulacky     Canon LS-123K-MYL   239  1579368875
262  https://www.czc.cz/  kalkulacky    Casio FX 7400 G II  1599  1579368875
218  https://www.czc.cz/  kalkulacky   Casio DJ 120 D PLUS   379  1579368875
263  https://www.czc.cz/  kalkulacky              HP Prime  3999  1579368875

[264 rows x 5 columns]